Class101/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('teacher_portal/',include('TeacherPortal.urls')),
    path('student_portal/',include('StudentPortal.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

StudentPortal/urls.py
from django.urls import path
from . import views
app_name = "student_portal"
urlpatterns = [
    path('student_detail/',views.studentDetail,name="student_detail"),
    path('logout/',views.logout,name="logout"),
    path('class_detail/<int:id>/',views.classDetail,name='class_detail'),
    path('class_detail/<int:id>/students',views.students,name="students"),
]

account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('',views.Welcome.as_view(), name="welcome"),
    path('teacher-registration/',views.TeacherRegistration.as_view(),name='teacher-register'),
    path('student-registration/',views.StudentRegistration.as_view(),name='student-register'),
]

StudentPortal/models.py
from django.db import models

# Create your models here.

StudentPortal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import auth
from TeacherPortal.models import CreateClass
from account.models import Student


# Create your views here.
def studentDetail(request):
    student = Student.objects.get(user=request.user)
    classes = reversed(CreateClass.objects.filter(student=student))

    if request.method == 'POST':
        student.student_profile_pic = request.FILES['edit_profile']
        student.save()
        return redirect('student_portal:student_detail')

    context = {
        'classes':classes,
        'student':student,
    }
    return render(request,'StudentPortal/student_detail_page.html',context)

def logout(request):
    auth.logout(request)
    return redirect('account:welcome') 

def classDetail(request,id):
    student = Student.objects.get(user=request.user)
    context = {
        'class_detail': get_object_or_404(CreateClass, pk=id),
        'student':student,
        'id':id,
    }
    return render(request,'StudentPortal/class_detail.html',context)

def students(request,id):
    student = Student.objects.get(user=request.user)
    classroom = get_object_or_404(CreateClass,pk=id)
    students = classroom.student.all().order_by("name")
    context = {
        'class_detail': get_object_or_404(CreateClass, pk=id),
        'student':student,
        'id':id,
        'students' : students,
    }
    return render(request,'StudentPortal/students.html',context)

StudentPortal/templates/StudentPortal/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Class101 | {% block title %} {% endblock title %} </title>
    <link rel="stylesheet" href="{% static './TeacherPortal/css/base.css' %}">
    {% block link %} {% endblock link %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a id="sub-header" class="navbar-brand" href="{% url 'student_portal:class_detail' id %}">{{class_detail.subject_name}}</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link text-dark" aria-current="page" href="{% url 'student_portal:class_detail' id %}">Stream</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" aria-current="page" href="#">classwork</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'student_portal:students' id %}">Students</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="#">Grades</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'student_portal:logout' %}">logout</a>
              </li>
            </ul>
            
          </div>
          <div>
              <button style="margin-right:5px;" id="profile-btn">
                {% if student.student_profile_pic %}
                    <img  style="width: 50px; height: 50px; border-radius: 50%;" src="{{ student.student_profile_pic.url }}" alt="profile">
                {% else %}
                  <img  style="width: 50px; height: 50px; border-radius: 50%;"
                  src="{% static './StudentPortal/images/user.png' %}"
                  alt="Profile"
                  />
                {% endif %}
              </button>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
           </div>
        </div>
      </nav>


      {% block content %}

      {% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

StudentPortal/templates/StudentPortal/class_detail.html
{% extends 'StudentPortal/base.html' %}
{% load static %}

{% block title %} {{class_detail.subject_name}} {% endblock title %}

{% block link %} <link rel="stylesheet" href="{% static './StudentPortal/css/stream.css' %}"> {% endblock link %}

{% block content %} 
    <section>
        <div id="stream">
            <div id="class-detail-container" class="bg-primary">
                <h4>
                    Subject Name: <span style="text-decoration: underline;">{{class_detail.subject_name}}</span>
                </h4>
                <h4>Class Name: <span style="text-decoration: underline;">{{class_detail.class_name}}</span></h4>
                <h4>Faculty Name: <span style="text-decoration: underline;">{{class_detail.teacher}}</span></h4>
            </div>
            
            <div id="announcement">
                <div id="user-profile-image">
                    <button class="btn border-0">
                        {% if student.student_profile_pic %}
                            <img  style="width: 50px; height: 50px; border-radius: 50%;" src="{{ student.student_profile_pic.url }}" alt="profile">
                        {% else %}
                            <img  style="width: 50px; height: 50px; border-radius: 50%;"
                            src="{% static './StudentPortal/images/user.png' %}"
                            alt="Profile"
                            />
                        {% endif %}
                    </button>
                </div>
                <div id="announcement-text">
                    Announce something to your class students
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

StudentPortal/templates/StudentPortal/student_detail_page.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Class101</title>
    <link rel="stylesheet" href="{% static './StudentPortal/css/student_detail_page.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a href="#" class="navbar-brand text-info"><h1>Class101</h1></a>
          <div>
            <button style="margin-right:5px;" class="btn border-0" data-bs-toggle="modal" data-bs-target="#profileModal">
              {% if student.student_profile_pic %}
              <img  style="width: 50px; height:50px; border-radius: 50%;" src="{{ student.student_profile_pic.url }}" alt="">
              {% else %}
              <img  style="width: 50px; height: 50px; border-radius: 50%;"
              src="{% static './StudentPortal/images/user.png' %}"
              alt="Profile"
              />
              {% endif %}
            </button>
         </div>
        </div>
      </nav>

      <section>
        <div class="modal right fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button class=" btn border-0 mx-auto d-block" data-bs-toggle="modal" data-bs-target="#editProfileImageModal" >
                  {% if student.student_profile_pic %}
                    <img  style="width: 100px; height: 100px; border-radius: 50%;" src="{{ student.student_profile_pic.url }}" alt="">
                  {% else %}
                    <img  style="width: 100px; height: 100px; border-radius: 50%;"
                    src="{% static './StudentPortal/images/user.png' %}"
                    alt="Profile"
                    />
                  {% endif %}
                </button>
                
              </div>
              <div class="modal-footer">
                <a class="btn btn-primary mx-auto d-block" href="{% url 'student_portal:logout' %}">Logout from account</a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div class="modal fade " id="editProfileImageModal" tabindex="-1" aria-labelledby="editProfileImageModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content  bg-dark">
              <div class="modal-header flex-column text-light">
                <div>
                  <h3>Profile Picture</h3>
                </div>
                <div>
                  <p >A picture helps people recognize you and lets you know when you’re signed in to your account</p>
                </div>
              </div>
              <div class="modal-body">
                {% if student.student_profile_pic %}
                  <img  class="mx-auto d-block" style="width: 320px; height: 320px; border-radius: 50%;" src="{{ student.student_profile_pic.url }}" alt="">
                {% else %}
                  <img class="mx-auto d-block" style="width: 320px; height: 320px; border-radius: 50%;"
                  src="{% static './StudentPortal/images/user.png' %}"
                  alt="Profile"
                  />
                {% endif %}
              </div>
              <div class="modal-footer justify-content-around">
                <form action="" method="post"  enctype="multipart/form-data">
                  {% csrf_token %}
                  <input type="file" name="edit_profile" id="fileInput" >
                  <input name="edit_image" type="submit" class="btn btn-outline-primary" value="Edit image">
                </form>
                <!-- <button  data-bs-dismiss="modal" onclick="document.getElementById('fileInput').click();">Edit image</button> -->
                
                <button type="button" class="btn btn-outline-primary">Remove</button>
              </div>
            </div>
          </div>
        </div>
      </section>
  

      <section id="classes-section">
        <div id="classroom">
          {% for class in classes %}
          <div class="class-cards">
            <div
              class="class-name bg-info"
            >
              <h4>
                <a href="{% url 'student_portal:class_detail' class.id %}">{{class.subject_name}}</a>
              </h4>
              <p>{{class.class_name}}</p>
              <p>{{class.teacher}}</p>
            </div>
          </div>
          {% endfor %}
        </div>
      </section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

StudentPortal/templates/StudentPortal/students.html
{% extends 'StudentPortal/base.html' %}
{% load static %}

{% block title %} Students {% endblock title %}

{% block link %} <link rel="stylesheet" href="{% static './StudentPortal/css/students.css' %}"> {% endblock link %}

{% block content %}
    <section>
        <div id="student-container">
            <div id="student-header" class="text-primary">
                <div>
                    <h4 class="mx-auto d-block">Student</h4>
                </div>
                <div>
                    <p class="mx-auto d-block">{{students.count}} students</p>
                </div>
            </div>
            {% for student in students %}
              <div id="show-students">
                  <div id="user-profile-image">
                      <button class="btn border-0">
                          <img  style="width: 30px; height: 30px; border-radius: 50%;"
                          src="{% static './StudentPortal/images/user.png' %}"
                          alt="Profile"
                          />
                      </button>
                  </div>
                  <div id="student-name">
                      {{student.name}}
                  </div>
              </div>
            {% endfor %}
        </div>
    </section>
{% endblock content  %}