Class101/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('teacher_portal/',include('TeacherPortal.urls')),
    path('student_portal/',include('StudentPortal.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TeacherPortal/urls.py
from django.urls import path
from . import views

app_name = "teacher_portal"
urlpatterns = [
    path('teacher_detail/',views.teacherDetail,name="teacher_detail"),
    path('logout/',views.logout,name='logout'),
    path('class_detail/<int:id>/',views.classDetail ,name='class_detail'),
    path('class_detail/<int:id>/students/',views.students,name='students'),
    path('class_detail/<int:id>/classwork/',views.classwork,name='classwork'),
]

account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('',views.Welcome.as_view(), name="welcome"),
    path('teacher-registration/',views.TeacherRegistration.as_view(),name='teacher-register'),
    path('student-registration/',views.StudentRegistration.as_view(),name='student-register'),
]

TeacherPortal/models.py
from statistics import mode
from django.db import models
from account.models import Teacher,Student

# Create your models here.

class CreateClass(models.Model):
    teacher = models.ForeignKey(Teacher,related_name="class_teacher",on_delete=models.CASCADE,null=True)
    student = models.ManyToManyField(Student)
    class_name = models.CharField(max_length=255,null=False)
    section = models.CharField(max_length=255)
    subject_name = models.CharField(max_length=255)

    def __str__(self):
        return (self.section+" | "+self.subject_name)

class Assignment(models.Model):
    classroom = models.ForeignKey(CreateClass,on_delete=models.CASCADE)
    title = models.CharField(max_length=255,blank=False,null=False)
    description = models.TextField(blank=True)
    assignment_file = models.FileField(upload_to="classroom/assignment",blank=False)

    def __str__(self):
        return (self.classroom.subject_name + " | " + self.title)

TeacherPortal/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from TeacherPortal.models import Assignment, CreateClass
from account.models import Student, Teacher
from django.contrib.auth.models import auth
from django.contrib import messages

# Create your views here.
def teacherDetail(request):
    teacher = Teacher.objects.filter(user=request.user).first()
    teacher_name = request.user.username
    if request.method == 'POST':
        if request.POST.get('create_class'):
            class_name = request.POST['class_name']
            section = request.POST['section']
            subject_name = request.POST['subject_name']

            if class_name == "":
                messages.warning(request,'class name is empty ')
                return redirect('teacher_portal:teacher_detail')

            new_class = CreateClass.objects.create(teacher=teacher,class_name=class_name,section=section,subject_name=subject_name)
            new_class.save()
            return redirect('teacher_portal:teacher_detail')

        if request.POST.get('edit_image'):
            teacher.teacher_profile_pic = request.FILES['edit_profile']
            teacher.save()
            return redirect('teacher_portal:teacher_detail')
    
    

    classes = reversed(CreateClass.objects.filter(teacher=teacher))
    context = {
        'teacher':teacher,
        'teacher_name':teacher_name,
        'classes':classes
    }

    return render(request,'TeacherPortal/teacher_detail_page.html',context)

def logout(request):
    auth.logout(request)
    return redirect('account:welcome')  


def classDetail(request,id):
    teacher = Teacher.objects.filter(user=request.user).first()
    context = {
        'class_detail': get_object_or_404(CreateClass, pk=id),
        'teacher':teacher,
        'id':id,
    }
    
    return render(request,'TeacherPortal/class_detail.html',context)

def students(request,id):
    teacher = Teacher.objects.filter(user=request.user).first()
    if request.method == 'POST':
        email = request.POST['email']
        roll_no = request.POST['roll_no']
        if Student.objects.filter(email=email,roll_no=roll_no).exists():
            student = Student.objects.filter(email=email,roll_no=roll_no).first()
            current_class = CreateClass.objects.get(teacher=teacher,pk=id)
            current_class.student.add(student)
            current_class.save()
            return redirect('teacher_portal:students',id=id)
        else:
            messages.error(request, 'student does not exist')


    context = {
        'class_detail': get_object_or_404(CreateClass, pk=id),
        'teacher':teacher,
        'id':id,
    }
    return render(request,'TeacherPortal/students.html',context)

def classwork(request,id):
    teacher = Teacher.objects.filter(user=request.user).first()
    classroom = get_object_or_404(CreateClass,pk=id)
    
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        assignment_file = request.FILES['assignment_file']
        assignment = Assignment.objects.create(classroom=classroom,title=title,description=description,assignment_file=assignment_file)
        assignment.save()

    assignments = reversed(Assignment.objects.filter(classroom=classroom))


    context = {
        'class_detail': get_object_or_404(CreateClass, pk=id),
        'teacher':teacher,
        'id':id,
        'assignments':assignments,
    }
    
    return render(request,'TeacherPortal/classwork.html',context)

TeacherPortal/templates/TeacherPortal/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Class101 | {% block title %} {% endblock title %} </title>
    <link rel="stylesheet" href="{% static './TeacherPortal/css/base.css' %}">
    {% block link %} {% endblock link %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a id="sub-header" class="navbar-brand" href="{% url 'teacher_portal:class_detail' id %}"> {{class_detail.subject_name}} </a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link text-dark" aria-current="page" href="{% url 'teacher_portal:class_detail' id %}">Stream</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" aria-current="page" href="{% url 'teacher_portal:classwork' id %}">classwork</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'teacher_portal:students' id %}">Students</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="#">Grades</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-dark" href="{% url 'teacher_portal:logout' %}">logout</a>
              </li>
            </ul>
            
          </div>
          <div>
              <button style="margin-right:5px;" id="profile-btn">
                {% if teacher.teacher_profile_pic %}
                    <img  style="width: 50px; height: 50px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="profile">
                {% else %}
                  <img  style="width: 50px; height: 50px; border-radius: 50%;"
                  src="{% static './TeacherPortal/images/user.png' %}"
                  alt="Profile"
                  />
                {% endif %}
              </button>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
           </div>
        </div>
      </nav>


      {% block content %}

      {% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

TeacherPortal/templates/TeacherPortal/class_detail.html
{% extends 'TeacherPortal/base.html' %}
{% load static %}

{% block title %} {{class_detail.subject_name}} {% endblock title %}

{% block link %} <link rel="stylesheet" href="{% static './TeacherPortal/css/stream.css' %}"> {% endblock link %}

{% block content %} 
    <section>
        <div id="stream">
            <div id="class-detail-container" class="bg-primary">
                <h4>
                    Subject Name: <span style="text-decoration: underline;">{{class_detail.subject_name}}</span>
                </h4>
                <h4>Class Name: <span style="text-decoration: underline;">{{class_detail.class_name}}</span></h4>
                <h4>Faculty Name: <span style="text-decoration: underline;">{{class_detail.teacher}}</span></h4>
            </div>
            
            <div id="announcement">
                <div id="user-profile-image">
                    <button class="btn border-0">
                        {% if teacher.teacher_profile_pic %}
                            <img  style="width: 50px; height: 50px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="profile">
                        {% else %}
                            <img  style="width: 50px; height: 50px; border-radius: 50%;"
                            src="{% static './TeacherPortal/images/user.png' %}"
                            alt="Profile"
                            />
                        {% endif %}
                    </button>
                </div>
                <div id="announcement-text">
                    Announce something to your class students
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

TeacherPortal/templates/TeacherPortal/classwork.html
{% extends 'TeacherPortal/base.html' %}
{% load static %}

{% block title %} Classwork {% endblock title %}

{% block link %} <link rel="stylesheet" href="{% static './TeacherPortal/css/classwork.css' %}"> {% endblock link %}

{% block content %}
    <section>
       <div id="classwork-container">
            <div id="assign-container">
                <div style="font-size: 2em; color:green;">
                    Classwork
                </div>
                <div>
                    <button id="assign-task-btn" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#assignWorkModal"><i class="fa fa-plus" style="color: white; "></i> Assign Task</button>
                </div>
            </div>
            {% for assignment in assignments %}
            <div id="show-assignment-conatiner">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="flush-headingOne"></h2>
                    <button class="btn border-0 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                      <div id="assignment-info-container" style="color: green;">
                        <i id="file-icon" class="fa fa-file-text-o"></i>
                        {{assignment.title}}
                      </div>
                    </button>
                  </h2>
                  <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                      <a id="assignment-file-link" target="_blank" href="{{assignment.assignment_file.url}}">
                        <p>{{assignment.title}} | 
                          {{assignment.description}}
                        </p>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
       </div>
    </section>
    <section>
        <div class="modal fade" id="assignWorkModal" tabindex="-1" aria-labelledby="assignWorkModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen">
              <div class="modal-content">
                <div class="modal-header">
                  <div id="jasg" class="modal-title" id="assignWorkModalLabel"><i id="file-icon" class="fa fa-file-text-o"></i>Assignment</div>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div id="modal-body" class="modal-body" style="background-color: #f8f9fa;">
                  <form id="assignment-form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="form" >
                        <input type="text" name="title" id="" placeholder="Title">
                        <Textarea placeholder="Description" name="description"></Textarea>
                        <input type="file" name="assignment_file" accept=".pdf,.docx">
                    </div>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <input name="assignment" type="submit" value="Assign" class="btn btn-primary" form="assignment-form">
                </div>
              </div>
            </div>
          </div>
    </section>
{% endblock content %}

TeacherPortal/templates/TeacherPortal/students.html
{% extends 'TeacherPortal/base.html' %}
{% load static %}

{% block title %} Students {% endblock title %}

{% block link %} <link rel="stylesheet" href="{% static './TeacherPortal/css/students.css' %}"> {% endblock link %}

{% block content %}
    <section>
        <div id="students-container">
            <div id="add-container">
                <div style="font-size: 2em; color:green;">
                    Students
                </div>
                <div class="add-student-icon">
                    <button id="add-student-icon" class="btn border-0" data-bs-toggle="modal" data-bs-target="#addStudentModal"><img style="width: 30px; height: 30px; border-radius: 50%;" src="{% static './TeacherPortal/images/student.png' %}" alt=""></button>
                </div>
            </div>
            {% for student in class_detail.student.all %}
              <div id="show-students">
                  <div id="user-profile-image">
                      <button class="btn border-0">
                          <img  style="width: 30px; height: 30px; border-radius: 50%;"
                          src="{% static './TeacherPortal/images/user.png' %}"
                          alt="Profile"
                          />
                      </button>
                  </div>
                  <div id="student-name">
                      {{student.name}}
                  </div>
                  <div>
                      <div class="options">
                          <button id="options" class="btn border-0"><img style="width: 30px; height: 30px; border-radius: 50%;" src="{% static './TeacherPortal/images/three-dots.png' %}" alt=""></button>
                      </div>
                  </div>
              </div>
            {% endfor %}
        </div>
    </section>

    <section>
        <div class="modal fade" id="addStudentModal" tabindex="-1" aria-labelledby="addStudentModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="addStudentModalLabel">Add Student</h5>
                </div>
                <div class="modal-body">
                  <form action="" method="post" id="add-student-form">
                    {% csrf_token %}
                    <input type="email" placeholder="email" name="email">
                    <br>
                    <input type="text" placeholder="Enrollment No" name="roll_no">
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn border-0" data-bs-dismiss="modal">Close</button>
                  <input type="submit" value="Add Student" class="btn btn-primary" form="add-student-form">
                </div>
              </div>
            </div>
          </div>
    </section>
{% endblock content %}

TeacherPortal/templates/TeacherPortal/teacher_detail_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Class101</title>
    <link
      rel="stylesheet"
      href="{% static './TeacherPortal/css/teacher_detail_page.css' %}"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <h1><a href="#" class="text-info" style="text-decoration:none ;">Class101</a></h1>
        <div>
          <button id="create-class-btn" class="btn border-0">
            <img style="width: 30px; height:30px;"
              src="{% static './TeacherPortal/images/plus.png' %}"
              alt="Make-class"
            />
          </button>
          <button class="btn border-0"  id="profile-btn" data-bs-toggle="modal" data-bs-target="#profileModal">
            {% if teacher.teacher_profile_pic %}
              <img style="width: 50px; height:50px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="">
            {% else %}
              <img style="width: 50px; height:50px; border-radius: 50%;"
              src="{% static './TeacherPortal/images/user.png' %}"
              alt="Profile"
              />
            {% endif %}
            
          </button>
       </div>
      </div>
    </nav>
    <!-- <nav>
      <div id="navbar">
        <div id="class101">
          
        </div>
        <div id="nav-components">
          <button id="create-class-btn">
            <img
              src="{% static './TeacherPortal/images/plus.png' %}"
              alt="Make-class"
            />
          </button>
          <button  id="profile-btn" data-bs-toggle="modal" data-bs-target="#profileModal">
            {% if teacher.teacher_profile_pic %}
              <img style="width: 50px; height:50px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="">
            {% else %}
              <img style="width: 50px; height:50px; border-radius: 50%;"
              src="{% static './TeacherPortal/images/user.png' %}"
              alt="Profile"
              />
            {% endif %}
            
          </button>
        </div>
      </div>
    </nav> -->

    <!-- profile modal -->

    <section>
      <div class="modal right fade" id="profileModal" tabindex="-1" aria-labelledby="profileModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button class=" btn border-0 mx-auto d-block" data-bs-toggle="modal" data-bs-target="#editProfileImageModal" >
                {% if teacher.teacher_profile_pic %}
                <img  style="width: 100px; height: 100px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="">
                {% else %}
                <img  style="width: 100px; height: 100px; border-radius: 50%;"
                src="{% static './TeacherPortal/images/user.png' %}"
                alt="Profile"
                />
                {% endif %}
              </button>
              
            </div>
            <div class="modal-footer">
              <a class="btn btn-primary mx-auto d-block" href="{% url 'teacher_portal:logout' %}">Logout from account</a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- edit profile image modal -->

    <section>
      <div class="modal fade " id="editProfileImageModal" tabindex="-1" aria-labelledby="editProfileImageModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content  bg-dark">
            <div class="modal-header flex-column text-light">
              <div>
                <h3>Profile Picture</h3>
              </div>
              <div>
                <p >A picture helps people recognize you and lets you know when you’re signed in to your account</p>
              </div>
            </div>
            <div class="modal-body">
              {% if teacher.teacher_profile_pic %}
                <img  class="mx-auto d-block" style="width: 320px; height: 320px; border-radius: 50%;" src="{{ teacher.teacher_profile_pic.url }}" alt="">
              {% else %}
                <img class="mx-auto d-block" style="width: 320px; height: 320px; border-radius: 50%;"
                src="{% static './TeacherPortal/images/user.png' %}"
                alt="Profile"
                />
              {% endif %}
            </div>
            <div class="modal-footer justify-content-around">
              <form action="" method="post"  enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="edit_profile" id="fileInput" >
                <input name="edit_image" type="submit" class="btn btn-outline-primary" value="Edit image">
              </form>
              <!-- <button  data-bs-dismiss="modal" onclick="document.getElementById('fileInput').click();">Edit image</button> -->
              
              <button type="button" class="btn btn-outline-primary">Remove</button>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div id="create-new-class">
        <form action="" class="create-new-class-form" method="post">
          {% csrf_token %}
          <label>Class Name <span style="color: red">*</span></label>
          <input
            type="text"
            class="input-field"
            name="class_name"
            placeholder="class name"
          />

          <label>Section</label>
          <input
            type="text"
            class="input-field"
            name="section"
            placeholder="section"
          />

          <label>Subject Name</label>
          <input
            type="text"
            class="input-field"
            placeholder="subject name"
            name="subject_name"
          />
          <div id="form-btn">
            <input name="create_class" type="submit" value="create class" id="submit-btn" />
            <button class="cancel-btn">cancel</button>
          </div>
          <!-- <input type="submit" value="create class" id="submit-btn"> -->
        </form>
      </div>
    </section>

    <section id="classes-section">
      <div id="classroom">
        {% for class in classes %}
        <div class="class-cards">
          <div
            class="class-name bg-info"
          >
            <h4>
              <a href="{% url 'teacher_portal:class_detail' class.id %}">{{class.subject_name}}</a>
            </h4>
            <p>{{class.class_name}}</p>
            <p>{{teacher_name}}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>

    <script>
      document
        .getElementById("create-class-btn")
        .addEventListener("click", function () {
          document.getElementById("create-new-class").style.display = "flex";
          document.body.style.overflow = "hidden";
        });
      document
        .getElementsByClassName("cancel-btn")
        .addEventListener("click", function () {
          document.getElementById("create-new-class").style.display = "none";
          document.body.style.overflow = "auto";
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>